### ISSUE TITLE
How mTCP deals with non-TCP packets read from dpdk/netmap?

### ISSUE THREAD

**Issue by ShahHemalB** [eunyoung14/mtcp#106]

**Comment by ajamshed** [comment]
The mTCP stack currently can respond to ping messages (ICMP). Also, it can send and receive ARP messages. For all other non-TCP protocols, the packets are silently dropped by the stack. We do plan to extend the mTCP stack so that it can send and receive DNS messages. But I am not sure when that implementation will be done.

**Comment by ShahHemalB** [comment]
Hi Asim,

Thanks for your prompt response, really appreciate it.
I have few follow-up queries.

1. Is it possible to by-pass instead of dropping the non-TCP packets with the current design in m-TCP? That is if those are non-TCP packets forward it to the actual destination instead of dropping it.
2. In one of the query I read that mTCP is planing to support UDP. Are there such plans? If yes, do we have any rough time lines?

Thanks

**Comment by ajamshed** [comment]
1- It should be possible to pass non-TCP packets to the kernel through the kni interface. But the code for that is currently absent from the mTCP stack. I plan to look into this some time in the future.

2- Yes. But it is difficult to give a certain deadline. I hope to implement this along with other missing features once I get free time. We have a list of TODOs mentioned in this page: https://github.com/eunyoung14/mtcp/wiki/Supported-Features.

By the way, we welcome git pull requests and code patches from all users. :)
