### ISSUE TITLE
Flow distribution across cores by packet I/O in mTCP approach

### ISSUE THREAD

**Issue by GopinathSadhu** [eunyoung14/mtcp#108]
As I understand the design of mTCP, 
1) Application thread attached to one of the core and initiates mTCP calls.
2) mTCP maintains one dedicated thread for each core (i.e, MTCPRunThread). 
3) mTCP also maintains per core data structures (i.e, mtcp_manager). 

Cache coherency issues are solved with this approach as application thread and mTCP thread is on same core, which share data using per core data structures. But what is the guarantee that mTCP thread gets same flow data that it is actually serving?

Example:
Say for 2 core machine.
1) Application threads are AP_T1, AP_T2.
2) mTCP thread will be created for each core say mTCP_T1, mTCP_T2.
3) Say AP_T1 is serving FLOW1(SrcPort1, SrcIP1, DstPort1, DstIP1) and AP_T2 is serving FLOW2(SrcPort2, SrcIP1, DstPort2, DstIP2). note: both are on for same network interface.
4) AP_T1, mTCP_T1, FLOW1 are on core 1 and AP_T2, mTCP_T2, FLOW2 are on core 2. 
5) mTCP_T1 & mTCP_T2 threads keeps polling on Packet I/O for incoming packets.
What is the guarantee that mTCP_T1 always gets FLOW1 data? and same case for other mTCP_T2 aswell.
(As I understand, Packet I/O equally distributes the packets to all cores for load balancing, so in the process, it is not guaranteed that mTCP thread gets only data that it is actually serving).

Thank YoU,
Gopinath.

**Comment by ajamshed** [comment]
We are using **symmetric** RSS to load balancing incoming traffic across cores. Please see 

http://www.ran-lifshitz.com/2014/08/28/symmetric-rss-receive-side-scaling/, or 
http://www.ndsl.kaist.edu/~kyoungsoo/papers/TR-symRSS.pdf, or
section 3.2 of http://www.ndsl.kaist.edu/~kyoungsoo/papers/mobisys13_woo.pdf

for details.

**Comment by GopinathSadhu** [comment]
Hello Ajamshed,
 Thanx for your quick reply.
I agree RSS part, where one flow is always sent to same core always. But what is the gurantee that on same core corresponding mTCP & application threads reside?

Thank You,
Gopinath.

**Comment by ajamshed** [comment]
I am not sure I understood your question. But maybe the following explanation may help. 

For server-case:
S-RSS will make sure that a connection first seen by core 'x' (where 'x' is >=0, 'x' <= 'number of cores') stay in the same core throughout the lifetime of the connection (irrespective of the flow direction).

For client-case:
We call [mtcp_init_rss()](http://shader.kaist.edu/mtcp/man/mtcp_init_rss.html) to choose the right source port so that the packets of 1 connection stay in the same core throughout the connection lifetime. I suggest that you go through ``epwget.c`` code to see how the function can be used.

I hope this helps.

**Comment by GopinathSadhu** [comment]
Hello Ajamshed,
  Server side:
   FilterSYNPacket() checks listener sockets on only one core (addr = &mtcp->listener->socket->saddr;) (i.e, the core on which mtcp_create_context() API is called).
NIC card distributes incoming packets based on S-RSS, as per S-RSS logic incoming SYN packet has chance to end up in different core than what MTCPRunThread() thread is residing. In that case SYN packet will be processed by different core and it will be dropped.
**If that is the case TCP connection can not be established. -> Please confirm this.**

Client side:
 I agree when mtcp_connect is called, source port is selected such that hash entry on 4 tuple results the same core.
Again NIC also has to use same hash algorithm as that of mtcp library so that NIC pushes further packets to same per core queue on which MTCPRunThread is running.
**Please confirm my understanding (using same hash algorithm at NIC) on client is is correct or not.**

Thank You,
Gopinath.

**Comment by ajamshed** [comment]
Each core is running an mTCP thread. And each mTCP thread context has its own dedicated ``mtcp`` struct. This means that each thread on the server side has a listening (passive) socket capable of accepting connections (Have you used [``SO_REUSEPORT``](https://lwn.net/Articles/542629/) option in BSD sockets? The listening socket behavior is similar to this).

You are right about the 2nd point. We make sure that we use the same hash function in the software level as the one the NIC uses for computing the queue-id.

**Comment by GopinathSadhu** [comment]
Hello Ajamshed,
 [Server Side] I understand SO_RESUEPORT option which is used to improve performance in multi thread environment.
What if server application is single threaded one, in that case only one core will be running mTCP thread. So in that case NIC hash function can produce core that may not match with application core number. In that case that complete connection itself will be dropped. How this problem can be solved here?

Thank You,
Gopinath.

**Comment by ajamshed** [comment]
In that case, you have two options. Both are a bit ugly.

1) You can hack ``io_module.c`` & ``config.c`` files, and develop some logic so that you only need to set 1 hardware queue for the NIC and bind it to CPU 0. All other cores will be idle and not part of mTCP application.

OR,

2) You can disable all CPUs except CPU 0 from ``sysfs`` (``/sys/devices/system/cpu/cpu[1~n]``) and re-run mTCP app just as it is.
