### ISSUE TITLE
Miscalculation for out of order Seq number

### ISSUE THREAD

**Issue by GroBam** [eunyoung14/mtcp#11]
Hi guys, I'm facing problems in receiving packets out of order when rcv_wnd is small

Here the case:
Assuming we have next Seq is rcv_nxt = X and window now is rcv_wnd = 3500
There are 4 pkts coming with Seq: X, X + 500, X + 1500, X + 2500 with respective length: 500, 1000, 1000, 1000.

Let's begin: First come is pkt (X + 500), len = 1000 so rcv_wnd = 2500
Next is pkt (X + 1500), len = 1000 => rcv_wnd = 1500
Now to pkt (X + 2500), len = 1000 => problem happened!

In tcp_in.c, function ValidateSequence, there is a condition:
if (!TCP_SEQ_BETWEEN(seq + payloadlen, cur_stream->rcv_nxt, 
				cur_stream->rcv_nxt + cur_stream->rcvvar->rcv_wnd - 1))

According to it, (X + 2500 + 1000) is out of range (X, X + 1500 -1) => FALSE and resend ACK

The problem happened because the variable rcv_wnd is not represent the buf range that payload will fit into so it make the SEQ validation wrong

I'm thinking of adding a variable to struct tcp_stream to deal with this scenario but I still hope you can fix it soon

Best Regards,
Quy

**Comment by eunyoung14** [comment]
Hi Quy. Thank you for reporting this issue.
I guess we are miscalculating receive window size at ProcessTCPPayload() in tcp_in.c.
The receive window should have been (buffer size - merged_len) instead of (buffer size - last_len).
We are also setting window size as (buffer size - 1) to null-terminate the ring buffer, but I think we won't need to do it.
If we fix the issue as above, the additional variable might not be necessary.
(X + 2500 + 1000) will be in [X, X + 3500].
I'll try to test this and post the fix, but it could take some time.

**Comment by eunyoung14** [comment]
This issue has been solved.
