### ISSUE TITLE
why we need a lock in mtcp_epoll_wait

### ISSUE THREAD

**Issue by littletiny** [eunyoung14/mtcp#119]
I am puzzle about some source code.
The design of mtcp is:  per application thread per mtcp thread
But, i found  <code> pthread_mutex_lock(&ep->epoll_lock) </code> in mtcp_epoll_wait,
The ep is a field of mtcp, the mtcp is a per thread variable
In this case, why should mtcp hold a lock in mtcp_epoll_wait? 

A application thread need to block in the epoll wait until a read/write/error event occur
So we need a condtion lock to block and wake up the application thread?

**Comment by ajamshed** [comment]
You are right. There are two threads running on each core: the application thread (that runs your main application logic), and the mtcp thread (that handles network communication, the TCP stack etc.). The mtcp thread needs to pass events such as ``EPOLLIN`` (incoming read) to the application thread, while
the application thread has to process those events. Both these threads need to gain exclusive access to the epoll descriptor resource before passing information to each other (obvious source of contention). That's why we need locks. See ``core.c`` (mtcp thread side locks) and ``eventpoll.c`` (application thread side locks) for details.

**Comment by littletiny** [comment]
Thank you for your response.
