### ISSUE TITLE
Is it OK to create per core context before creating per core thread?

### ISSUE THREAD

**Issue by WenqingWu** [eunyoung14/mtcp#127]
I am trying to port Nginx to mTCP. 
Nginx will create connection pool during initialization, which means nginx creates all the listening sockets before running per core worker process. 
When porting nginx to mTCP, for example, I need to replace socket(int domain,int type, int protocol) with
mtcp_socket(mctx_t mctx, int domain,int type, int protocol). But I haven't create per core context. Is it OK to create per core context before creating per core thread?

**Comment by ajamshed** [comment]
I have quickly browsed through the code. I think it may be possible. In the worst case, I recommend that you go through ``mtcp_create_context()`` function definition present in ``core.c``. Please let me know if you face any issues.

By the way, a generous volunteer submitted nginx-mtcp code late last year via email to me. I have been planning to upload that to the GitHub repository. But I haven't been able to find time. If you want, I can email you that code for reference. But you'll probably have to update the code slightly so that it supports the latest version of mTCP.

**Comment by WenqingWu** [comment]
Hi, ajamshed!
Thank you for your reply. I'll try the solution.
I will be appreciated if you email me the nginx-mtcp code. And my email is wenqingwu2015@gmail.com

**Comment by ajamshed** [comment]
Sure. I will email you the reference code soon.
