### ISSUE TITLE
run MTCP on AARCH64 linux on Arm A-53 Processor

### ISSUE THREAD

**Issue by vlsireddy** [eunyoung14/mtcp#159]
Hi,
   what does it take to run the MTCP on Arm A-53 processor [cross compiled on AARCH64 Linux]. I see dpdk support is not there yet on Arm Processors and also the packet IO engine seems to be completely Intel architecture based.  Can i cross compile MTCP using AARCH64 linux and others, does it work ?

Thanks

**Comment by ajamshed** [comment]
Hi visireddy,

I am not familiar with Arm A-53 processor. Is this the one?: https://developer.arm.com/products/processors/cortex-a/cortex-a53

Based on the description, it is based on Armv8-A architecture. In that case, I would suggest trying out dpdk compilation with `arm-armv7a-linuxapp-gcc` target. But first, please check whether you are able to run sample dpdk applications (present in `examples` subdirectory).

**Comment by vlsireddy** [comment]
Hi,
   So one has to have dpdk working in kernel to use MTCP working at user space ?, please confirm?

Thanks

**Comment by ajamshed** [comment]
To run mTCP applications, you would have to insert only 1 dpdk-specific kernel module called ``igb_uio.ko``. (It needs a dependent ``uio.ko`` module). For normal rx/tx, operations, the dpdk driver runs completely in user space.

**Comment by khemendra0** [comment]
Hi Jamshed,

I am looking for mtcp ARM Processor Ecosystem for support, test features, performance in reference with ARM processor.

Does mtcp has support for ARM v8 version?
Does performance tested on intel but not for ARM ?

I am interested on mtcp on ARM.

Plz share your suggestions...

Thanks a lot :)

**Comment by ajamshed** [comment]
Some researchers from the Institute of Computing Technology, Chinese Academy of Sciences very kindly shared us the code for mTCP that runs on arm64 processors via [odp](http://opendataplane.org/). We were not able to test the code ourselves since we did not have access to an arm host. The code is available in arm-odp branch. You are more than welcome to test that version out and make the necessary changes to get the stack working for your hardware. In case you have mTCP-related questions, you can contact me. For ARM-specific changes to the stack, please contact @lybmath.
