### ISSUE TITLE
how to adjust mTCP receive window to receive larger packet

### ISSUE THREAD

**Issue by vincentmli** [eunyoung14/mtcp#19]
Hi,

I noticed when using mTCP as tcp client, from wireshark, the 3WHS final ack always advertise receive window size as 114 bytes and in each ACK of tcp server data, the receive window size is advertised as 64 bytes, this leads to tcp server sending small packet like 64 bytes data to mTCP client. I looked through the mTCP code, I see nowhere hard coded 64 bytes receive window size, could you give me a  direction where I can change mTCP for larger receive window size?

i increased  mtcp configuration file rcvbuf value that seems have some effect on the receive window size, but still not big engough, say set rcvbuf to 32768, the ACK receive window size increased to 256 bytes, I would like to increase the receive window size up to at least 1 full tcp segment size like 1460 bytes for testing 

Thanks

**Comment by eunyoung14** [comment]
Hi Vincent,
The advertised window size by ACK is scaled. On three way handshake, mTCP notifies the peer the window scale value through TCP option. Since the default window scale for mTCP is set to 7, 256 bytes of advertised window means that it has 256 X 2^7 = 32768 bytes of receive window. So your modification to the configuration file is well applied to mTCP. It seems that the server is not parsing TCP window scale option.

**Comment by vincentmli** [comment]
you are absolutely right, I forgot to check if the server negotiated window scaling or not in 3WHS, apparently the server didn't after I double check. sorry for the noise.
