### ISSUE TITLE
Maybe a bug in RaisePendingStreamEvents

### ISSUE THREAD

**Issue by fomy** [eunyoung14/mtcp#201]
```
	if (socket->epoll & MTCP_EPOLLOUT) {
		struct tcp_send_vars *sndvar = stream->sndvar;
		if (!sndvar->sndbuf || 
				(sndvar->sndbuf && sndvar->sndbuf->len < sndvar->snd_wnd)) {
			if (!(socket->events & MTCP_EPOLLOUT)) {
				TRACE_EPOLL("Socket %d: Adding write event\n", socket->id);
				AddEpollEvent(ep, USR_SHADOW_EVENT_QUEUE, socket, MTCP_EPOLLOUT);
			}
		}
	}
```

Hi,

I notice that only when sndvar->sndbuf->len < sndvar->snd_wnd, mtcp will raise an event.
Should this condition be sndvar->snd_wnd > 0?

Thanks

**Comment by eunyoung14** [comment]
Hi, this block checks whether there is send buffer available. 

1. mTCP's sending buffer is created on demand. If `sndbuf` is null, it means that there was no prior `mtcp_write` call and we can create new send buffer in the future.
2. If sending buffer is already present, it checks whether there is enough room in the buffer. If the length of payloads in the buffer is less than the send window, it means that the app can send more data.

If one of those two conditions is satisfied, mTCP raises an `MTCP_EPOLLOUT` event so that the application can send. If `sndvar->snd_wnd` is 0, I think the application shouldn't send anything.

**Comment by fomy** [comment]
Sure.

But your code is 
> sndvar->sndbuf->len < sndvar->snd_wnd

rather than
`sndvar->snd_wnd > 0`

**Comment by fomy** [comment]
Here is the code where snd_wnd is calculated:

`sndvar->snd_wnd = sndvar->sndbuf->size - sndvar->sndbuf->len;`

**Comment by eunyoung14** [comment]
Now it makes sense! I was confused a little before you edited the comment.
I'll fix the condition to `sndvar->snd_wnd > 0`. Thanks for reporting.
