### ISSUE TITLE
Possible to change BLOCKING_SUPPORT in mtcp.h from FALSE to TRUE?

### ISSUE THREAD

**Issue by alex1230608** [eunyoung14/mtcp#25]
Hi mtcp developer,

I'm going to implement a server with a listener thread responsible for accepting new incoming clients. All the child sockets would be assigned to other threads so that the listener thread can keep accepting.
(I know another way to implement this is epoll, which I've tried, but I want to perform experiments on this one for some reason)

However, I found that the BLOCKING_SUPPORT flag is FALSE in mtcp.h. 
Does this flag correspond to the blocking of accept, read, write? That is, The thread calling them will be blocked if there is no corresponding event in the queues. (without calling mtcp_setsock_nonblock)
Is it OK if I change it from FALSE to TRUE?

Sincerely,
Alex

**Comment by eunyoung14** [comment]
Hi Alex,

The BLOCKING_SUPPORT flag is depreciated and not supported any more.
Turning it to TRUE will not enable blocking function calls. It was
maintained only at the first time of development for debugging TCP.

In addition, mTCP only allows using one application thread per a mtcp
context. Accessing an mtcp_epoll structure from multiple threads could
raise race condition since mTCP uses lock-free data structures for single
producer single consumer.

Thanks,
EunYoung

2015-11-04 14:59 GMT+09:00 alex1230608 <notifications@github.com>:

**Comment by alex1230608** [comment]
Ok. Thanks for the reply!
