### ISSUE TITLE
tcp connection load balance with mtcp

### ISSUE THREAD

**Issue by bhpike65** [eunyoung14/mtcp#27]
I saw dpdk had a load-balance example, but it seems not all i need.
is there a way to do tcp load balance with multi processes?

Thanks.

**Comment by arunkumarsit** [comment]
Is multi-process is supported in mTCP now?
Till DPDK-2.0 integrated version, multi-processing was not fully supported by mTCP.

**Comment by bhpike65** [comment]
hi, arunkumarsit

i not work all things out,  but i think you just need do a tiny modification in the code.

**Comment by bhpike65** [comment]
btw,  i saw mtcp/util/rss.c have a few rss key to test, but why you guys finally choose the key which all byte filled with 0x05

**Comment by ajamshed** [comment]
Hi bhpike,

We tested mTCP with multiple processes a while back using Ethernet's flow director (we did it during dpdk-1.8.0/ days... I can send you an email if you need to know more details). We definitely have the implementation of multi-process support in our plans. It turns out that the fdir API for dpdk changed with the new dpdk-2.x release and we need to modify our modules before we can publicly release the code. We will let you know once we have an update in this regard. 

For more information regarding the RSS key, I would actually suggest that you read the following document that one of our co-authors wrote: http://an.kaist.ac.kr/~shinae/paper/2012-srss.pdf. I can summarise the findings of the report: if you set the RSS seed to have a repeated 16-bit pattern (in the case of the code, it is 0x0505), it would make the Toeplitz RSS algorithm flow-symmetric. The analysis in the report shows that you will not lose level of load balancing with the change of this pattern.
