### ISSUE TITLE
mTCP and C10M ?

### ISSUE THREAD

**Issue by simonhf** [eunyoung14/mtcp#6]
Can mTCP be used to achieve C10M [1] ? Can it be used to open 10 million (or more?) keepalive HTTP connections which send very little traffic, for example, for a chat server or notification server? If so, how to calculate the RAM overhead of each connection and/or keep it to a minimum?

[1] http://c10m.robertgraham.com/p/manifesto.html

**Comment by eunyoung14** [comment]
We've tested for a condition that has 1 million idle connections and thousands of active connections with mtcp-lighttpd and it worked well.
mTCP uses 336 bytes for a tcb struct.
Since the purpose is like chat server, let's suppose we use 4K buffer for each send and receive buffer.
Then the memory required for a connection will be (336B + 8 KB) = 8528B.
For 10 million open sessions, the total consumption will be 85.28 GB.
The actual memory usage could be a little higher.

**Comment by simonhf** [comment]
Thanks for the info. If my 10 million open sessions are mostly idle then is there a way with mtcp to only use the 8 KB on the *active* connections? And is there a way to further shrink the 336B per connection?

**Comment by eunyoung14** [comment]
It would be possible to allocate the buffers for only active connections with some modification.
Current implementation frees the buffer only when the connection is closed, but it could be changed to dynamically free the buffer if it's never used for certain period of time.
However, the 336B for tcb cannot be removed to maintain a connection information.

**Comment by simonhf** [comment]
In case nobody else implements this, then I volunteer to take on these changes once a netmap version of mTCP is available :-)

**Comment by eunyoung14** [comment]
That would be great!!
