### ISSUE TITLE
missing dpdk0 for a dpdk-compliant network card

### ISSUE THREAD

**Issue by ATCP** [eunyoung14/mtcp#70]
Hi, 

We build a dpdk-compliant network card that can be used for dpdk applications, but cannot assigned dpdk0 for that NIC using tools/setup_iface_single_process.sh when we port mtcp to use that NIC, like assigning dpdk# to NetXtreme II BCM5709 gigabit ethernet, we found that it also cannot be assigned a dpdk# using setup_iface_single_process.sh, so is there any way to make mtcp use that NIC, modify the files igb_uio.c/igb_uio.h ?

Thanks

**Comment by ajamshed** [comment]
I suggest that you look at igb_uio.h file. I patched up the igb_uio module to export net_device entries so that they could be visible to the kernel for simple statistics handling. For your custom card, you may have to add your PCI device entry (as a macro PCI_VDEVICE(..)).

Then you will have to update  retrieve_dev_addr() (which fetches the MAC address of the interface) and retrieve_dev_specs() that detects the underlying device.
