### ISSUE TITLE
can I use system call together with mtcp?

### ISSUE THREAD

**Issue by yangxiaozhenzxy** [eunyoung14/mtcp#71]
I know the mtcp API is just like the system call API,for
example:
mtcp_setsockopt   -   setsockopt
mtcp_socket   -   socket
mtcp_accept   -    accept
mtcp_bind   -   bind
mtcp_connect   - connect
but there is some system call API that mtcp does not offer corresponding APIs
for example:
getsockname
gethostbyname
getpeername
there is not some interface just like mtcp_getsockname,can I just use the system call
interface?

**Comment by ajamshed** [comment]
Unfortunately no. mTCP stack creates its own sockets and its descriptors that are different from BSD sockets. So you won't be able to use functions such as ```getsockname()``` with those sockets that have been created by mTCP. The easiest way will be to patch ```api.c``` to support those functions that do not currently exist. I think ```mtcp_getsockname()``` and ```mtcp_peername()``` will be very easy to implement.

```mtcp_gethostbyname()``` will be more challenging to develop since it may invoke a DNS query (which requires UDP protocol).
