### ISSUE TITLE
Will mtcp support udp in the future? 

### ISSUE THREAD

**Issue by wjm3219** [eunyoung14/mtcp#75]

**Comment by ajamshed** [comment]
My plan is to eventually write a stripped down version of UDP stack (similar to ARP/ICMP in mTCP) in the future. The target is to extend mTCP application so that it can communicate with a remote endpoint across gateways/routers. On top of that, the plan is to develop an API that can be used to send DNS lookup requests (DNS/UDP framework) to DNS servers.

**Comment by wjm3219** [comment]
So great! @ajamshed
