### ISSUE TITLE
affinity of the threads created by mtcp

### ISSUE THREAD

**Issue by jugean2** [eunyoung14/mtcp#92]
Hi,

I would like to bind the tasks created by mtcp to a particular core. How can I do it ?

I use mtcp with netmap. When I give the parameter core = 2 to mtcp_create_context(core), I get the following error :
[mtcp_create_context:1109] Failed initialize new mtcp context. Requested cpu id 2 exceed the number of cores 1 configured to use.

What's the use of mtcp_core_affinitize(core) ?

I use only 1 queue on my NIC (ixgbe) and the core I want to reach is reserved with isolcpu.

Thank you.

Cheers,

Julien.

**Comment by ajamshed** [comment]
There is currently a restriction in the mTCP stack. It implicitly assumes that the user is going to use core-id 0 if `total_cpus` configured is set to 1. The API will be improved in the future that eventually removes this restriction. For now, you can either use (a) core-id 0, OR (b) manually update core.c/netmap_module.c file so that core 2 can read traffic from NIC queue 1. 

mtcp_core_affinitize is a wrapper function of sched_setaffinity(..) and has a sanity check that you are quoting above.
