### ISSUE TITLE
ARP request time out

### ISSUE THREAD

**Issue by muziding** [eunyoung14/mtcp#97]
Hi,
I run epserver on multi-process mode, network interface is intel 82599. Each process will send ARP request packet, but only one process can receive ARP reply packet.
The log for not receive ARP reply packet process:
[  ARPTimer: 304] [CPU 1] ARP request timed out.
I want each process can receive ARP reply packet, Can someone please help me solve this problem?

**Comment by ajamshed** [comment]
Hi muziding,
Are you getting all the ARP response packets only on core 0?
This looks like an RSS-related bug. ARP packets may not get distributed to the right NIC queue as the dpdk driver is set to follow `ETH_RSS_TCP` policy. 

In the multi-threaded version, all mTCP core threads were sharing one global ARP table. That's why it worked for this mode.

I suggest that for the time being, please use static ARP entries for your setup. You can see how you can set them by referring to the config/arp.conf sample file. I will think of a good solution for this problem in the mean time.

**Comment by yulintao** [comment]
hi,
The function fdir of 82599  should be useful.

**Comment by ajamshed** [comment]
That's a good idea.
