### ISSUE TITLE
Bug in flows statistics 

### ISSUE THREAD

**Issue by muziding** [eunyoung14/mtcp#99]
Value of flows field is 1, when all of my TCP client has been  disconnected. And mTcp process can still work.
`[CPU 0] eth1 flows:      1, RX:       0(pps) (err:     0),  0.00(Gbps), TX:       0(pps),  0.00(Gbps), max_pkt_size: 99`
`[ ALL ] eth1 flows:      1, RX:       0(pps) (err:     0),  0.00(Gbps), TX:       0(pps),  0.00(Gbps)`

**Comment by muziding** [comment]
`mtcp->flow_cnt` may stay the same, when `tcp_stream` has been removed form `mtcp->timeout_list` in method of `CheckConnectionTimeout`. Maybe this is a bug, I think.

**Comment by ajamshed** [comment]
Thanks for reporting the bug. But we may need to know more details on how we can replicate the same problem in our testbed. Can you please share more details about your setup and connections?

**Comment by muziding** [comment]
I used mtcp in redis-server.  redis-benchmark as a tcp client.
Client startup commands like this:
redis-benchmark -h 10.1.1.10 -t set,get -q -l

**Comment by ajamshed** [comment]
Thanks. I will try to replicate the same problem and come up with a fix.

**Comment by muziding** [comment]
Hi, ajamshed!
Sometimes mTCP server will output `There are still not invalidate events remaining`, when TCP client has been disconnected.
I have used the following patch to fix it.
`Index: socket.c`
`===================================================================`
`--- socket.c	(revision 5)`
`+++ socket.c	(working copy)`
`@@ -65,6 +65,7 @@`
`    `
 ` socket->socktype = MTCP_SOCK_UNUSED;`
 ` socket->epoll = MTCP_EPOLLNONE;`
`+	socket->events = 0;`
`    `
`if (need_lock)`
` pthread_mutex_lock(&mtcp->ctx->smap_lock);`

I'm not sure if this is correct. So, I want to know why  we need to check `socket->events` in `AllocateSocket`. 
Can you tell me? Thanks.

**Comment by ajamshed** [comment]
Hmmm. I don't think that is the right fix. I think there is a reason why the `events` field is not reset to 0 once sockets are freed (maybe a pending event needs to be transferred from the mTCP thread context to application thread context for the connection that has already been terminated). I think it is better to comment out line socket.c:130 for the time being. It's been a while since I last touched this part of the code. Let me trace down the scenario where this warning message is printed and I'll get back to you.
